----
dist: trusty
language: node_js

# Use isolated build instance
sudo: required

before_install:
  - git clone https://github.com/YunoHost/package_linter /tmp/package_linter"

script:
  - /tmp/package_linter/package_linter.py ./
