packaging_format = 2

id = "abantecart"
name = "Abantecart"
description.en = "Open source ecommerce platform to power online retail"
description.fr = "Plateforme de commerce électronique pour la vente au détail en ligne"

version = "1.3.3~ynh1"

maintainers = []

[upstream]
license = "OSL-3.0"
website = "https://www.abantecart.com/"
demo = "https://www.abantecart.com/shopping-cart-demo"
admindoc = "https://docs.abantecart.com/"
userdoc = "https://abantecart.atlassian.net/wiki/spaces/AD/overview?homepageId=3506313"
code = "https://github.com/abantecart/abantecart-src"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"
    optional = false

[resources]
        [resources.sources.main]
        url = "https://github.com/abantecart/abantecart-src/archive/refs/tags/1.3.3.tar.gz"
        sha256 = "5b31282d148b0a8fa30b6f9c5af14b196bafafa3b8cc3dca8769ec610e985852"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server php8.2-iconv php8.2-mbstring php8.2-mysqli php8.2-zip php8.2-curl php8.2-gd php8.2-soap php8.2-xml libwebp-dev libfreetype6-dev libjpeg62-turbo-dev libmcrypt-dev libpng-dev libxpm-dev libonig-dev libzip-dev mc net-tools libxml2-dev"

    [resources.database]
    type = "mysql"
