packaging_format = 2

id = "abantecart"
name = "Abantecart"
description.en = "Open source ecommerce platform to power online retail"
description.fr = "Plateforme de commerce électronique pour la vente au détail en ligne"

version = "1.4.0~ynh1"

maintainers = []

[upstream]
license = "OSL-3.0"
website = "https://www.abantecart.com/"
demo = "https://www.abantecart.com/shopping-cart-demo"
admindoc = "https://docs.abantecart.com/"
userdoc = "https://abantecart.atlassian.net/wiki/spaces/AD/overview?homepageId=3506313"
code = "https://github.com/abantecart/abantecart-src"

[integration]
yunohost = ">= 11.2.20"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"
    optional = false

[resources]
        [resources.sources.main]
        url = "https://github.com/abantecart/abantecart-src/archive/refs/tags/1.4.0.tar.gz"
        sha256 = "2904375a91f70e2ecc26285010658bfb9f5d3ab1b56a8e398c4b3d27b8874fa3"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.3-iconv, php8.3-mbstring, php8.3-mysqli, php8.3-zip, php8.3-curl, php8.3-gd, php8.3-xml"

    [resources.database]
    type = "mysql"
