packaging_format = 2

id = "abantecart"
name = "Abantecart"
description.en = "Open source ecommerce platform to power online retail"
description.fr = "Plateforme de commerce électronique pour la vente au détail en ligne"

version = "1.3.2~ynh1"

maintainers = []

[upstream]
license = "OSL-3.0"
website = "https://www.abantecart.com/"
demo = "https://www.abantecart.com/shopping-cart-demo"
admindoc = "https://docs.abantecart.com/"
userdoc = "https://abantecart.atlassian.net/wiki/spaces/AD/overview?homepageId=3506313"
code = "https://github.com/abantecart/abantecart-src"

[integration]
yunohost = ">= 11.1.17"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"
    optional = false

[resources]
        [resources.sources.main]
        url = "https://github.com/abantecart/abantecart-src/archive/refs/tags/1.3.2.tar.gz"
        sha256 = "58ed9007054e5f74826d8ac5d3358d893c612af34e04877107c9baf81f6d529f"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    type = "mariadb-server php8.0-iconv php8.0-mbstring php8.0-mysqli php8.0-mysql php8.0-zip php8.0-soap curl wget git libwebp-dev libfreetype6-dev libjpeg62-turbo-dev libmcrypt-dev libpng-dev libxpm-dev libonig-dev libzip-dev mc net-tools libxml2-dev"

    [resources.database]
    type = "mysql"
