test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.4586e00bbf6ae98f49135623b282446613a9cb25.name = "Upgrade from 1.3.2"
