#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    # test_upgrade_from.4586e00bbf6ae98f49135623b282446613a9cb25.name = "Upgrade from 1.3.2"
    test_upgrade_from.98cb298bd976c1ffd8e690f6da61cda3170c393a.name = "Upgrade from 1.4.1~ynh1"
