#!/bin/bash

app=$YNH_APP_INSTANCE_NAME
set -u
# Source app helpers
source /usr/share/yunohost/helpers
source .fonctions

domain=$(ynh_app_setting_get $app domain)

ynh_mysql_drop_db $app

# Remove installed files
SECURE_REMOVE   '/var/www/${app}'
REMOVE_NGINX_CONF
REMOVE_FPM_CONF


# Remove app dependencies
if ynh_package_is_installed "abantecart-deps"; then
  ynh_package_autoremove "abantecart-deps"
fi


sudo service nginx reload
