#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source .fonctions
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
db_name=$(ynh_app_setting_get $app db_name)

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE THE SQL BDD
#=================================================

ynh_mysql_remove_db $db_name $db_name	# Suppression de la base de donnée et de l'utilisateur associé.

#=================================================
# REMOVE THE MAIN DIR OF THE APP
#=================================================

SECURE_REMOVE '/var/www/$app'	# Suppression du dossier de l'application

#=================================================
# REMOVE THE NGINX CONFIGURATION
#=================================================

REMOVE_NGINX_CONF	# Suppression de la configuration nginx

#=================================================
# REMOVE THE PHP-FPM CONFIGURATION
#=================================================

REMOVE_FPM_CONF	# Suppression de la configuration du pool php-fpm

#=================================================
# SPECIFIC REMOVE
#=================================================
# Remove app dependencies
#=================================================

if ynh_package_is_installed "abantecart-deps"; then
  ynh_package_autoremove "abantecart-deps"
fi

