#!/bin/bash

ynh_abort_if_errors
ynh_die --message="Users must upgrade manually as upgrade packaged are available only from the prior version to the next. Check out here: https://abantecart.atlassian.net/wiki/spaces/AD/pages/5275676/Upgrade+manually"